[package]
name = "krunner-cratesio"
version = "0.1.0"
edition = "2021"

[dependencies]
crates-io = "0.40.0"
curl = "0.4.46"
krunner = { version = "0.1.1", features = ["derive"] }
open = "5.1.2"
reqwest = { version = "0.12.3", features = ["json"] }
serde_json = "1.0.115"
